name: Merge to Release Branch
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [merged]
jobs:
  merge-master-to-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

    - name: Merge master to release
      run: |
          git fetch --unshallow

          # Delete release branch
          git branch -d release
          git push origin --delete release

          # Create new release branch
          git checkout -b release

    - name: Compile typescript
      run: |
          npm i typescript
          tsc
          git add .
          git commit -m 'Auto-compile typescript'
          git push --set-upstream origin release
