name: Delete Build Branch
on: 
  workflow_run:
    workflows: ["Create tags"]
    types:
      - completed

jobs:
  delete-build-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions" 

    - name: Delete build branch
      run: |
          git pull
          git branch -D api-build
          git push origin --delete api-build